# Generated by Django 4.1.3 on 2022-11-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=123456, max_length=30)),
                ('stock', models.IntegerField(default=1, max_length=30)),
                ('nombre', models.CharField(default='Articulo', max_length=50)),
                ('descripcion', models.CharField(default='Descripcion', max_length=200)),
                ('precio', models.IntegerField(default=100, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(default='2022-09-06')),
                ('fechaFin', models.DateField(default='2022-09-06')),
            ],
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('listaDeAsignacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confApp.asignaciones')),
            ],
        ),
        migrations.CreateModel(
            name='detalleVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numVenta', models.IntegerField(default=1234, max_length=30)),
                ('numArticulo', models.IntegerField(default=1234, max_length=30)),
                ('precioUnidad', models.IntegerField(default=1234, max_length=30)),
                ('cantidad', models.IntegerField(default=1234, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(default='Calle', max_length=30)),
                ('altura', models.IntegerField(default=12345, max_length=5)),
                ('barrio', models.CharField(default='Barrio', max_length=70)),
                ('provincia', models.CharField(default='Provincia', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=30)),
                ('horaInicio', models.IntegerField(default=8, max_length=2)),
                ('horaFin', models.IntegerField(default=20, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2022-09-06')),
                ('listaDetalleVenta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confApp.detalleventas')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(default='3513897259', max_length=20)),
                ('direccion', models.CharField(default='Direccion', max_length=50)),
                ('listaDeCaja', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confApp.cajas')),
            ],
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(default='46037183', max_length=8)),
                ('nombre', models.CharField(default='Nombre', max_length=30)),
                ('apellido', models.CharField(default='Apellido', max_length=30)),
                ('nacimiento', models.DateField(default='2022-09-06')),
                ('telefono', models.CharField(default='3513897259', max_length=20)),
                ('email', models.CharField(default='mailfalso@gmail.com', max_length=40)),
                ('direccion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confApp.direcciones')),
                ('listaAsignacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confApp.asignaciones')),
                ('sucursal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confApp.sucursal')),
                ('turnoTrabajo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confApp.turnos')),
            ],
        ),
        migrations.AddField(
            model_name='asignaciones',
            name='listaDeVenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confApp.ventas'),
        ),
    ]
