# Generated by Django 4.1.3 on 2022-11-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='codigo',
            field=models.IntegerField(default=123456),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='cantidad',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='numArticulo',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='numVenta',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='precioUnidad',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='altura',
            field=models.IntegerField(default=12345),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='horaFin',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='horaInicio',
            field=models.IntegerField(default=8),
        ),
    ]
