# Generated by Django 4.1.3 on 2022-11-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confApp', '0002_alter_articulos_codigo_alter_articulos_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='listaDetalleVenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confApp.detalleventas'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='confApp.direcciones'),
        ),
    ]
